services:
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    volumes:
      - ./:/application
      - ./sourcefiles/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"

  php-fpm:
    build: sourcefiles/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm
    working_dir: /application
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
    volumes:
      - ./:/application

  pgsql:
    image: postgres:13
    container_name: ${PROJECT_NAME}-pgsql
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:5432'

  vite:
    image: node:20-alpine
    container_name: ${PROJECT_NAME}-vite
    working_dir: /application
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./package.json:/application/package.json
      - ./package-lock.json:/application/package-lock.json
      - ./vite.config.js:/application/vite.config.js
      - ./tailwind.config.js:/application/tailwind.config.js
      - ./resources:/application/resources
      - ./public:/application/public
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
